include(":app")
/*include(":features:navigation")
include(":features:lookup")
include(":features:loading")
include(":features:controls")
include(":features:menu")
include(":features:settings")*/
include(":features:loading-api")
include(":features:auth-api")
include(":features:auth")
include(":domain")
include(":data:repository")
include(":data:datastore")
include(":data:local")
include(":libraries:core")
include(":libraries:test")

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
